# Generated by Django 6.0.3 on 2026-03-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('position', models.CharField(max_length=50, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('video', models.FileField(upload_to='video_lessons/')),
                ('number', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['number'],
            },
        ),
    ]
