# Generated by Django 6.0.3 on 2026-03-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_question_remove_testresult_created_at_attempt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True, verbose_name='Номер вопроса'),
        ),
    ]
